apiVersion: v1
kind: Pod
spec:
  containers:
  - name: helm
    image: alpine/helm:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
