apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-worker-ui
    image: gcr.io/${env.GCP_PROJECT}/chalk-ui-base:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "500m"
        memory: "3.0Gi"
