apiVersion: v1
kind: Pod
spec:
  containers:
  - name: helm
    image: alpine/helm:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "300m"
        memory: "0.5Gi"
