apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-worker-ui
    image: gcr.io/flipperkid-default/chalk-ui-base:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "300m"
        memory: "1Gi"
