{{- $fullName := include "..fullname" . -}}
{{- $accountName := include "..serviceAccountName" . -}}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ $fullName }}
spec:
  instanceRef:
    external: {{ include "..dbInstanceName" . }}

---

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ $fullName }}
spec:
  instanceRef:
    external: {{ include "..dbInstanceName" . }}
  password:
    valueFrom:
      secretKeyRef:
        key: db-password
        name: {{ $fullName }}-server

---

{{- if eq .Values.environment "DEV" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-db-restorer
  labels:
    {{- include "..labels" . | nindent 4 }}
    app.kubernetes.io/component: db-restorer
spec:
  template:
    metadata:
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-restorer
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "..serviceAccountName" . }}
      shareProcessNamespace: true
      containers:
      - name: cloud-sql-proxy
        image: us.gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
        - "--exit-zero-on-sigterm"
        - "--structured-logs"
        - "--port=5432"
        - {{ printf "%s:us-east4:%s" .Values.gcpProject (include "..dbInstanceName" .) | quote }}
        securityContext:
          runAsNonRoot: true
      - name: db-restorer
        image: {{ printf "us-east4-docker.pkg.dev/%s/default-gar/chalk-db-restorer:%s" .Values.gcpProject .Values.imageTag | quote }}
        env:
        - name: PGDATABASE
          value: {{ $fullName }}
        - name: PGUSER
          value: {{ $fullName }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $fullName }}-server
              key: db-password
        - name: USE_STARTER_DATA
          value: {{ .Values.useStarterData | quote }}
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
{{- end }}