{{- $fullName := include "..fullname" . -}}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ $fullName }}
spec:
  instanceRef:
    external: {{ include "..dbInstanceName" . }}

---

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ $fullName }}
spec:
  instanceRef:
    external: {{ include "..dbInstanceName" . }}
  password:
    valueFrom:
      secretKeyRef:
        key: db-password
        name: {{ $fullName }}-server
