{{- $fullName := include "..fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.environment "PROD" }}
    kubernetes.io/ingress.global-static-ip-name: "chalk-ip"
    {{- else if eq .Values.environment "DEV" }}
    kubernetes.io/ingress.global-static-ip-name: "chalk-dev-ip"
    {{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-server
              port:
                name: http
        - path: /admin_static/
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-server
              port:
                name: http
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-ui
              port:
                name: http
