{{- $fullName := include "..fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    {{- if .Values.DEV }}
    kubernetes.io/ingress.global-static-ip-name: "chalk-dev-ip"
    {{- else }}
    kubernetes.io/ingress.global-static-ip-name: "chalk-ip"
    {{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /api/*
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: http
        - path: /admin_static/*
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: http
        - path: /*
          backend:
            serviceName: {{ $fullName }}-ui
            servicePort: http
