{{- $fullName := include "..fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "chalk-ip"
spec:
  rules:
    - http:
        paths:
        {{- if .Values.DEV }}
        - path: /api/
          pathType: Prefix
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: http
        - path: /admin_static/
          pathType: Prefix
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: http
        - path: /
          pathType: Prefix
          backend:
            serviceName: {{ $fullName }}-ui
            servicePort: http
        {{- else }}
        - path: /api/*
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: http
        - path: /admin_static/*
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: http
        - path: /*
          backend:
            serviceName: {{ $fullName }}-ui
            servicePort: http
        {{- end }}
