{{- $fullName := include "..fullname" . -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: https-redirect
spec:
  redirectToHttps:
    enabled: true

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    {{- if or (eq .Values.environment "PROD") (eq .Values.environment "STAGING") }}
    kubernetes.io/ingress.global-static-ip-name: "chalk-ip"
    {{- else if eq .Values.environment "DEV" }}
    kubernetes.io/ingress.global-static-ip-name: "chalk-dev-ip"
    {{- end }}
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-cert-issuer"
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/v1beta1.FrontendConfig: "https-redirect"
spec:
  rules:
    - http:
        paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-server
              port:
                name: http
        - path: /admin_static/
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-server
              port:
                name: http
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-ui
              port:
                name: http
  tls:
  - hosts:
    {{- if or (eq .Values.environment "PROD") (eq .Values.environment "STAGING") }}
    - chalk.flipperkid.com
    {{- else if eq .Values.environment "DEV" }}
    - chalk-dev.flipperkid.com
    {{- end }}
    secretName: tls-cert
