apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-oauth
type: Opaque
data:
{{ if eq .Values.environment "STAGING" -}}
{{ (.Files.Glob "secrets.staging/*").AsSecrets | indent 2 }}
{{- else -}}
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end -}}
