apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-server
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.server.nginxPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "..serverSelectorLabels" . | nindent 4 }}
