apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-server
  labels:
    {{- include "..serverLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..serverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
      labels:
        {{- include "..serverSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: chalk-sa
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "..fullname" . }}-server
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: "gcr.io/flipperkid-default/chalk-server-image:latest"
          imagePullPolicy: Always
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/html/
          env:
            {{- include "..serverEnv" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}-server-cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            - "/cloud_sql_proxy"
            {{- if .Values.DEV }}
            - "-instances=flipperkid-default:us-east4:chalk-dev=tcp:5432"
            {{- else }}
            - "-instances=flipperkid-default:us-east4:chalk-prod=tcp:5432"
            {{- end }}
          securityContext:
            runAsNonRoot: true
        - name: {{ .Chart.Name }}-server-nginx
          image: nginx:stable
          imagePullPolicy: Always
          ports:
            - name: nginx-http
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
            - name: staticfiles
              mountPath: /var/www/html/
          readinessProbe:
            httpGet:
              path: /admin_static/rest_framework/css/default.css
              port: nginx-http
          livenessProbe:
            httpGet:
              path: /admin_static/rest_framework/css/default.css
              port: nginx-http
          resources:
            requests:
              cpu: 10m
        - name: {{ .Chart.Name }}-server
          image: "gcr.io/flipperkid-default/chalk-server-image:latest"
          imagePullPolicy: Always
          env:
            {{- include "..serverEnv" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/todos/todos/
              port: http
          readinessProbe:
            httpGet:
              path: /api/todos/todos/
              port: http
