apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-server-secrets
data:
  secret-key: {{ .Values.server.secretKey | b64enc }}
  db-password: {{ .Values.server.dbPassword | b64enc }}
