apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-server
data:
  db-password: {{ .Values.server.dbPassword | b64enc }}
  django-email: {{ .Values.server.djangoEmail | b64enc }}
  django-password: {{ .Values.server.djangoPassword | b64enc }}
  django-username: {{ .Values.server.djangoUsername | b64enc }}
  secret-key: {{ .Values.server.secretKey | b64enc }}
