apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-server
  labels:
    {{- include "..serverLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: nginx-http
      protocol: TCP
      name: http
  selector:
    {{- include "..serverSelectorLabels" . | nindent 4 }}
