apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-server
  labels:
    {{- include "..serverLabels" . | nindent 4 }}
spec:
{{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "..serverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "..serverSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "..fullname" . }}-server
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/html/
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
        - name: migrate
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command: ["python", "manage.py", "migrate"]
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}-server-nginx
          image: nginx:stable
          imagePullPolicy: IfNotPresent
          ports:
            - name: nginx-http
              containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
            - name: staticfiles
              mountPath: /var/www/html/
          readinessProbe:
            httpGet:
              path: /admin_static/rest_framework/css/default.css
              port: nginx-http
          livenessProbe:
            httpGet:
              path: /admin_static/rest_framework/css/default.css
              port: nginx-http
          resources:
            requests:
              cpu: 10m
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/todos/todos/
              port: http
          readinessProbe:
            httpGet:
              path: /api/todos/todos/
              port: http
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
