{{ $accountName := include "..serviceAccountName" . }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $accountName }}
spec:
  displayName: {{ $accountName }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ $accountName }}@{{ .Values.gcpProject }}.iam.gserviceaccount.com
  name: {{ $accountName }}
  labels:
    {{- include "..labels" . | nindent 4 }}

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ $accountName }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ $accountName }}
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.gcpProject }}.svc.id.goog[default/{{ $accountName }}]

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ $accountName }}-project-iam-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ .Values.gcpProject }}
  memberFrom:
    serviceAccountRef:
      name: {{ $accountName }}
  role: roles/cloudsql.editor

---

{{- if eq .Values.environment "DEV" -}}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ $accountName }}-db-backup-bucket-iam-policy
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: {{ .Values.gcpProject }}-db-backups
  memberFrom:
    serviceAccountRef:
      name: {{ $accountName }}
  role: roles/storage.objectViewer
  {{- end}}