apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 8000;
      server_name {{ .Values.domain }};
      client_max_body_size 4G;
      keepalive_timeout 300;
      charset utf-8;

      location = /auth_test {
          internal;
          proxy_pass http://{{ include "..fullname" . }}-server:8001/api/todos/auth_test/;
          proxy_pass_request_body off;
          proxy_set_header Content-Length "";
          proxy_set_header X-Original-URI $request_uri;
          proxy_set_header X-Original-Remote-Addr $remote_addr;
          proxy_set_header X-Original-Host $host;
      }

      location @auth {
          return 302 /api/todos/auth/;
      }

      location /healthz/ {
          add_header Content-Type text/plain;
          add_header Cache-Control no-cache;
          expires 0;
          return 200 'Healthy!';
      }

      location / {
          # Static assets for React frontend
          # Local on the "app" container
          alias /www/client/;
          add_header Cache-Control no-cache;
          expires 0;

          auth_request /auth_test;
          error_page 403 @auth;
      }

      # access_log /var/log/nginx/access.log combined;
      # error_log  /var/log/nginx/error.log warn;
    }
