{{- $fullName := include "..fullname" . -}}
{{- $healthz := "http" -}}
{{- if eq .Values.environment "DEV" -}}
  {{- $healthz = "expo-debugger" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "..uiLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..uiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
      labels:
        {{- include "..uiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-ui
          {{- if eq .Values.environment "DEV" }}
          image: {{ printf "gcr.io/%s/chalk-ui-dev:%s" .Values.gcpProject .Values.imageTag | quote }}
          {{- else }}
          image: {{ printf "gcr.io/%s/chalk-ui:%s" .Values.gcpProject .Values.imageTag | quote }}
          {{- end }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-ui
                  key: sentry-dsn
            - name: SENTRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-ui
                  key: sentry-token
            - name: DEBUG
            {{- if eq .Values.environment "DEV" }}
              value: 'true'
            {{- else }}
              value: 'false'
            {{- end }}
            {{- if eq .Values.environment "DEV" }}
            - name: REACT_NATIVE_PACKAGER_HOSTNAME
              value: {{ .Values.ui.hostIp }}
            {{- end }}
          ports:
            - name: http
              containerPort: 19006
              protocol: TCP
          {{- if eq .Values.environment "DEV" }}
            - name: expo-devtools
              containerPort: 19002
              protocol: TCP
            - name: expo-debugger
              containerPort: 19000
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ $healthz }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ $healthz }}
          startupProbe:
            httpGet:
              path: /
              port: {{ $healthz }}
            failureThreshold: 60
          {{- if eq .Values.environment "DEV" }}
          # TODO (jordan) figure resource limits for containers
          resources:
            limits:
              cpu: 750m
              memory: 2Gi
          {{- end}}
