apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    {{- include "..uiLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..uiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
      labels:
        {{- include "..uiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-ui
          {{- if .Values.DEV }}
          image: "gcr.io/flipperkid-default/chalk-ui-image-dev:latest"
          {{- else }}
          image: "gcr.io/flipperkid-default/chalk-ui-image-prod:latest"
          {{- end }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 19006
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 60
