{{- $fullName := include "..fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "..uiLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..uiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
      labels:
        {{- include "..uiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-ui
          {{- if eq .Values.environment "DEV" }}
          image: "gcr.io/flipperkid-default/chalk-ui-image-dev:latest"
          {{- else }}
          image: "gcr.io/flipperkid-default/chalk-ui-image-prod:latest"
          {{- end }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-ui
                  key: sentry-dsn
            - name: SENTRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-ui
                  key: sentry-token
            - name: DEBUG
            {{- if eq .Values.environment "DEV" }}
              value: 'true'
            {{- else }}
              value: 'false'
            {{- end }}
          ports:
            - name: http
              containerPort: 19006
              protocol: TCP
          {{- if eq .Values.environment "DEV" }}
            - name: expo
              containerPort: 19002
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 60
