{{- $fullName := include "..fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "..uiLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..uiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..uiSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ $fullName }}-ui
      containers:
        - name: ui
          image: {{ printf "us-east4-docker.pkg.dev/%s/default-gar/chalk-ui:%s" .Values.gcpProject .Values.imageTag | quote }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
          readinessProbe:
            httpGet:
              path: /healthz/
              port: http
