apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    {{- include "..uiLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "..uiSelectorLabels" . | nindent 4 }}
