apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-ui-secrets
data:
  environment: {{ .Values.ui.environment | b64enc }}
  sentry-dsn: {{ .Values.ui.sentryDsn | b64enc }}
  sentry-token: {{ .Values.ui.sentryToken | b64enc }}
