apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    {{- include "..uiLabels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 19010
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..uiSelectorLabels" . | nindent 4 }}
