# Generated by Django 3.0.7 on 2020-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
