# Generated by Django 3.2.5 on 2021-10-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_labelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmodel',
            name='todo_set',
            field=models.ManyToManyField(related_name='label_set',
                                         to='todos.TodoModel'),
        ),
    ]
