# Generated by Django 6.0 on 2026-02-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_moreworklabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltodomodel',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
