# Generated by Django 6.0 on 2026-02-16 13:35

import chalk.todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_historicaltodomodel_version_todomodel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelmodel',
            name='name',
            field=models.TextField(
                help_text=
                'Label name (max 50 characters, alphanumeric + spaces + common punctuation)',
                validators=[chalk.todos.models.validate_label_name]),
        ),
    ]
