# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_alter_labelmodel_options_alter_labelmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltodomodel',
            name='snoozed_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='snoozed_until',
            field=models.DateTimeField(null=True),
        ),
    ]
