apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server-secret-key
  annotations:
    kubernetes.io/credentials-description: "Secret key for Django config used for continuous deployment of Chalk"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.server.secretKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server-db-password
  annotations:
    kubernetes.io/credentials-description: "DB password used for continuous deployment of Chalk"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.server.dbPassword }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-permitted-users
  annotations:
    kubernetes.io/credentials-description: "Permitted users of the app for continuous deployment of Chalk"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.permittedUsers }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sentry-dsn
  annotations:
    kubernetes.io/credentials-description: "Sentry DSN used for continuous deployment of Chalk"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.sentry_dsn }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sentry-token
  annotations:
    kubernetes.io/credentials-description: "Sentry token used for continuous deployment of Chalk"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.sentry_token }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth-web-client-json
  annotations:
    kubernetes.io/credentials-description: "OAuth secret for web logins used by Chalk build"
  labels:
    jenkins.io/credentials-type: "secretFile"
type: Opaque
stringData:
  filename: oauth_web_client_secret.json
data:
  data: |-
{{ if eq .Values.environment "STAGING" -}}
{{ .Files.Get "secrets.staging/oauth_web_client_secret.json" | b64enc | indent 4 }}
{{- else -}}
{{ .Files.Get "secrets/oauth_web_client_secret.json" | b64enc | indent 4 }}
{{- end }}

---

# This isn't for the prod continuous deployment
# It's used by the CI tests to login
# I'm including here for expediency
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth-refresh-token
  annotations:
    kubernetes.io/credentials-description: "Oauth refresh token used for the integration tests of Chalk"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.chalk_oauth_refresh_token }}
