apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server-secret-key
  annotations:
    kubernetes.io/credentials-description: "Secret key for Django config used for continuous deployment of prod"
  labels:
    jenkins.io/credentials-type: "secretText"
stringData:
  text: {{ .Values.server.secretKey }}
