apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-worker-python
    image: python:3
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "1000m"
        memory: "1.5Gi"

