apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
  - name: dind
    image: docker:24.0.6-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
    resources:
      requests:
        cpu: "600m"
        memory: "3Gi"
      limits:
        cpu: "1000m"
        memory: "3Gi"
  volumes:
  - name: dind-storage
    emptyDir: {}
