# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
gcpProject: ""

# DEV, CI, STAGING, or PROD
environment: DEV

ui:
  sentryDsn:
  sentryToken:

server:
  dbPassword:
  djangoEmail:
  djangoPassword:
  djangoUsername:
  secretKey:
