# Base container for building UI
# We run this weekly and use the result to speed up builds
# Performs yarn install to cache JS dependencies
FROM node:14-alpine
WORKDIR /js

# Install system packages for dev tooling
RUN apk add --no-cache bash g++ make python3

# Install React dependencies
COPY js/yarn.lock .
COPY js/package.json .
RUN yarn install --pure-lockfile
