# JS container for running dev server
# TODO (jordan) Look into DRYing this & Dockerfile out w/ Docker Buildkit
FROM node:14-alpine
WORKDIR /js

# Install system packages for dev tooling
RUN apk add --no-cache bash g++ make python3

# Install React dependencies
COPY js/yarn.lock .
COPY js/package.json .
RUN yarn install --pure-lockfile

# Copy configs for tooling
COPY js/.prettierrc .
COPY js/.eslintrc .
COPY js/jest.config.js .
COPY js/tsconfig.json .
COPY js/.storybook ./.storybook

# Copy source files
COPY Makefile /
COPY js/app.json ./app.json
COPY js/App.tsx ./App.tsx
COPY js/assets ./assets
COPY js/src ./src

CMD ["yarn", "web"]
