# JS container for running dev server
# TODO (jordan) Look into DRYing this & Dockerfile out w/ Docker Buildkit
FROM gcr.io/flipperkid-default/chalk-ui-base:latest
WORKDIR /js

# Install system packages for dev tooling
# RUN apk add --no-cache bash g++ make python3
RUN apt-get update && apt-get install -y \
  bash \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

# Install React dependencies
COPY js/yarn.lock .
COPY js/package.json .
RUN yarn install --pure-lockfile && yarn cache clean

# Copy configs for tooling
COPY js/.prettierrc .
COPY js/.eslintrc .
COPY js/babel.config.js .
COPY js/jest.config.js .
COPY js/tsconfig.json .
COPY js/.storybook ./.storybook

# Copy source files
COPY Makefile /
COPY js/web ./web
COPY js/app.config.js ./app.config.js
COPY js/App.tsx ./App.tsx
COPY js/assets ./assets
COPY js/src ./src

# Set CI true so we don't add a ton of watchers in Expo
# TODO revisit this when working on hot reloading / dev setup
ENV CI=true
CMD ["yarn", "web"]
