# JS container for running dev server
# TODO (jordan) Look into DRYing this & Dockerfile out w/ Docker Buildkit
FROM node:14
WORKDIR /js

# Install system packages for dev tooling
# RUN apk add --no-cache bash g++ make python3
RUN apt-get update && apt-get install -y \
  bash \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

# Install React dependencies
COPY js/yarn.lock .
COPY js/package.json .
RUN yarn install --pure-lockfile && yarn cache clean

# Copy configs for tooling
COPY js/.prettierrc .
COPY js/.eslintrc .
COPY js/jest.config.js .
COPY js/tsconfig.json .
COPY js/.storybook ./.storybook

# Copy source files
COPY Makefile /
COPY js/app.json ./app.json
COPY js/App.tsx ./App.tsx
COPY js/assets ./assets
COPY js/src ./src

ENV REACT_NATIVE_PACKAGER_HOSTNAME localhost
ENV EXPO_DEVTOOLS_LISTEN_ADDRESS 0.0.0.0
CMD ["yarn", "web"]
