name: CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_rrweb_ingest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_gen/dev-requirements.txt

    - name: Run tests with pytest
      run: |
        cd test_gen
        python -m pytest -v feature_extraction/tests rrweb_ingest/tests session_stitching/tests
