name: "Repo Visualizer"

on:
  workflow_dispatch: {}
  push:
    # The branches below must be a subset of the branches above
    branches:
      - github_actions
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.8.2
        with:
          excluded_paths: ".github"
